### PR TITLE
Stats

### PR DESCRIPTION
**Pull request by angrybee**
This branch adds the vsearch functions fastq_stats, fastq_eestats and fastq_eestats2 to the plugin.

Input are single- or paired-end fastq files. Stats are from all forward/reverse reads over all samples.
The two new functions additional use the system command zcat and support multiprocessing. The output is a visualization which offers the different files for download. Data are also implemented as iframe or html table.

~~Missing: The unit tests. Manual diff with vsearch output was okay.~~

### CODE REVIEW

**Comment by ebolyen** [comment]
Hey @angrybee! Let us know when this is ready for review, I may take a quick pass shortly, but in any case, thanks for contributing!

**Comment by angrybee** [comment]
Hi @ebolyen ! I think you can do a first review. Functionality, basic visualization of the data, and unit tests are implemented and working.

File: q2_vsearch/_stats.py [hunk 1]
```diff
@@ -0,0 +1,131 @@
+# ----------------------------------------------------------------------------
+# Copyright (c) 2019, Sabine Hurka (sabine.hurka@sabine-hurka.de)
```
Comment (thermokarst) [inline q2_vsearch/_stats.py]: Can you change this to:

```suggestion
# Copyright (c) 2016-2019, QIIME 2 development team.
```

The "QIIME 2 development team" includes all contributors, yourself included. You can put a note below this header regarding authorship of the code, if you wish --- your call!

File: q2_vsearch/_stats.py [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+            filename = os.path.join(output_dir, filename)
+            data_df = pd.read_csv(filename, sep='\t')
+            html[direction][stats_type] = q2templates.df_to_html(data_df,
+                                                                 index=False)
+    return(html)
+
+
+def _fastq_stats(output_dir: str, sequences, threads, paired=False) -> None:
+    # read manifest and add complete path
+    manifest = pd.read_csv(os.path.join(str(sequences),
```
Comment (thermokarst) [inline q2_vsearch/_stats.py]: A safer way to do this is to `view` the manifest as a Dataframe, check out [this snippet](https://github.com/qiime2/q2-cutadapt/blob/70084a9ede42343511b89c57afa9e3ca51c734df/q2_cutadapt/_trim.py#L141-L148) for an example.

File: q2_vsearch/assets/fastq_eestats2.html [hunk 3]
```diff
@@ -0,0 +1,24 @@
+{% extends "tab-child.html" %}
+
+{% block content %}
+<div class="row">
+    <div class="col-lg-12">
+        <h1>vsearch - fastq_eestats2</h1>
+        {% set colsize = 6 if paired else 12 %}
+        <div class="col-lg-{{ colsize }}">
```
Comment (thermokarst) [inline q2_vsearch/assets/fastq_eestats2.html]: Missing a parent `<div class="row">` above, which is causing bootstrap to render a little strangely in the viz.

File: q2_vsearch/assets/fastq_stats.html [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+{% block content %}
+<div class="row">
+    <div class="col-lg-12">
+        <h1>vsearch - fastq_stats</h1>
+        {% set colsize = 6 if paired else 12 %}
+        <div class="col-lg-{{ colsize }}">
+            <h4>Forward Reads</h4>
+            <a href={{ datafiles.forward.stats }}>Download as TXT</a>
+            <p style="margin-top: 15px">
+                <iframe src="{{ datafiles.forward.stats }}" frameborder="0" height="600px" width="95%"></iframe>
```
Comment (thermokarst) [inline q2_vsearch/assets/fastq_stats.html]: The `iframe` is pretty clunky and I think is a bit difficult to use. How about instead making this a `pre`:

image

File: q2_vsearch/plugin_setup.py [hunk 5]
```diff
@@ -427,4 +429,46 @@
                  'documentation.')
 )
 
+plugin.visualizers.register_function(
+    function=q2_vsearch._stats.fastq_stats_paired,
+    inputs={
+        'sequences': SampleData[PairedEndSequencesWithQuality],
+    },
+    parameters={
+        'threads': qiime2.plugin.Int % qiime2.plugin.Range(
```
Comment (thermokarst) [inline q2_vsearch/plugin_setup.py:442]: Instead of making 0 a magic value, how about we do something like this, instead?

```suggestion
        'threads': qiime2.plugin.Int % qiime2.plugin.Range(1, None) | qiime2.plugin.Str % qiime2.plugin.Choices(['auto'])
```

**Review by thermokarst — CHANGES_REQUESTED** [review]
Hey there @angrybee, thanks so much for this! I took a preliminary pass through, and have some comments (inline). Please let me know if you have any questions or comments. As well, we will be freezing repos for release on July 29th, with the release scheduled some time for July 30th. If this PR doesn't make it in this cycle, it can get moved to the 2019.10 cycle. Thanks!

File: q2_vsearch/assets/fastq_stats.html (hunk 4 above)
Comment (angrybee) [reply q2_vsearch/assets/fastq_stats.html]: I looked at it with `pre`, looks nicer, more contrast, better to read.

But what is the clunky part of it for you? Scrolling both files independent from each other? Or both files side by side? In my use case files have different number of lines so I need to go to different heights. Here, I need a scrollbar for each file and want them side by side to make my decisions.

vsearch01

File: q2_vsearch/plugin_setup.py (hunk 5 above)
Comment (angrybee) [reply q2_vsearch/plugin_setup.py:442]: I get errors with this code on version 2019.4 while doing `qiime dev refresh-cache`.

If we change it, should other code in this file be changed for multi threading too? I was using the style of the other functions.

```
Traceback (most recent call last):
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/builtin/dev.py", line 31, in refresh_cache
    q2cli.core.cache.CACHE.refresh()
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 76, in refresh
    self._state = self._get_cached_state(refresh=True)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 103, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 240, in _get_current_state
    state['plugins'][name] = self._get_plugin_state(plugin)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 262, in _get_plugin_state
    state['actions'][id] = self._get_action_state(action)
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 279, in _get_action_state
    data = {'name': name, 'repr': self._get_type_repr(spec.qiime_type),
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/q2cli/core/cache.py", line 346, in _get_type_repr
    if style.expr.predicate is not None:
  File "/homes/shurka/miniconda3/envs/qiime2-2019.4.dev/lib/python3.6/site-packages/qiime2/core/type/grammar.py", line 58, in __getattr__
    % (type(self), name))
AttributeError: <class 'qiime2.core.type.grammar.UnionExp'> object has no attribute 'predicate'
```

File: q2_vsearch/assets/fastq_eestats2.html (hunk 3 above)
Comment (angrybee) [reply q2_vsearch/assets/fastq_eestats2.html]: Sorry, I don’t get it. I compared the `html` with other visualizations. Every row has its `<div class=”row”>` or do you mean to get the headline an own `<div>`?

**Comment by angrybee** [comment]
Thank you @thermokarst for the review and input. I added some questions and comments :)

File: q2_vsearch/assets/fastq_eestats2.html (hunk 3 above)
Comment (thermokarst) [reply q2_vsearch/assets/fastq_eestats2.html]: The parent element for any columns should be a row (in bootstrap). Here, your col is nested directly inside another col.

File: q2_vsearch/plugin_setup.py (hunk 5 above)
Comment (angrybee) [reply q2_vsearch/plugin_setup.py:442]: Works with 2019.7. Changed only my part because there is some more work to be done in the code.

File: q2_vsearch/_stats.py [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+        process1.poll()
+        process2.poll()
+        if process1.returncode is not None and process2.returncode is not None:
+            process1.communicate(timeout=15)
+            break
+
+
+def _build_cmds(output_dir: str, filelist, direction='forward'):
+    datafiles = {direction: {}}
+    cmd = ['zcat'] + filelist
```
Comment (thermokarst) [inline q2_vsearch/_stats.py]: I am wary of relying on a system tool like this. Is it (or an alternative) available on conda? If so, please update and specify the dependency in the build recipe. If it is not, please refactor to use python stdlib. Also, I am a bit confused about _why_ this is here --- it looks like the `zcat` results are duplicated twice, but it doesn't look like the results are used anywhere - can you please comment on that?

Comment (angrybee) [reply q2_vsearch/_stats.py]: Hi thermokarst,
You are right about using `zcat` without being sure if it is installed.

zcat is used to get all reads over all samples of one direction as a pipe (line 25) which is used by the vsearch-command as input from stdin `-` (lines 26, 42). vsearch can handle only one gz-file ;(

Nonetheless, I refactored the code to use a python solution and also made it possible to reduce I/O when using more cores.

File: q2_vsearch/tests/test_stats.py [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+            default_filelist.extend(['fastq_stats_reverse.txt',
+                                     'fastq_eestats2_reverse.txt',
+                                     'fastq_eestats_reverse.txt'])
+        default_filelist.sort()
+
+        with tempfile.TemporaryDirectory() as output_dir:
+            if (paired):
+                obs = fastq_stats_paired(output_dir, self.input_seqs, threads)
+            else:
+                obs = fastq_stats_single(output_dir, self.input_seqs, threads)
```
Comment (Oddant1) [inline q2_vsearch/tests/test_stats.py]: Hello @angrybee :bee:! The variable `obs` doesn't appear to be used anywhere else in the code. Is it still necessary?

Comment (angrybee) [reply q2_vsearch/tests/test_stats.py]: :1st_place_medal: You found the magic relict of copy and paste! Thx for the review so far.

**Comment by thermokarst** [comment]
Thanks @angrybee! Sorry this took so long on our end, but it is being merged now, and will be released in the upcoming 2020.5 release of QIIME 2. Thanks!
